services:
  # A Docker web service
  - type: web
    name: ChatbotAssistant
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt && pip install frozendict --upgrade
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port 10000